version: '3'

services:
  # Database
  vart_db:
    image: vart_mysql:5.7
    volumes:
      - vart_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpvartsite
  # phpmyadmin
  vart_phpmyadmin:
    depends_on:
      - vart_db
    image: vart_phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9001:80'
    environment:
      PMA_HOST: vart_db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpvartsite
  # Wordpress
  vart_wordpress:
    depends_on:
      - vart_db
    image: vart_wordpress:latest
    ports:
      - '9000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: vart_db:3307
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpvartsite
networks:
  wpvartsite:
volumes:
  vart_db_data: